[target.thumbv7em-none-eabihf]
image = "ghcr.io/planet-community/planet-build-system-containers:latest-cosmo-codios-codios-cargo-thumbv7em-none-eabihf"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/planet-community/planet-build-system-containers:latest-cosmo-codios-codios-cargo-aarch64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/planet-community/planet-build-system-containers:latest-cosmo-codios-codios-cargo-x86_64-unknown-linux-musl"
