[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build_debug]
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf"]

[tasks.build_release]
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf", "--release"]

[tasks.doc]
command = "cargo"
args = ["doc"]

[tasks.test]
disabled = true

[tasks.build]
disabled = true

[tasks.codirs]
dependencies = [
    "format",
    "build_debug",
    "build_release",
    "doc"
]
