[toolchain]
channel = "nightly"
components = [
            "clippy-preview",
            "llvm-tools-preview",
            "rust-src",
            "rust-std",
            "rustfmt-preview",
            "rust-analyzer",
            "rustc"
]
targets = [
    "thumbv7em-none-eabihf",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]
