[toolchain]
channel = "nightly-2023-08-19"
components = ["rust-src", "rustfmt", "llvm-tools-preview"]
targets = [
    "thumbv7em-none-eabihf",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]
