[toolchain]
channel = "nightly-2024-04-11"
components = [
            "rust-src",
            "rustfmt-preview",
            "clippy-preview",
            "llvm-tools-preview",
            "rust-std"
]
targets = [
    "thumbv7em-none-eabihf",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]
