name: CoDiOS builder workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: CoDiOS build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cross-compiliation toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-09
          target: thumbv7em-none-eabihf
          override: true

      - name: If this build is a release, build in release mode
        uses: actions-rs/cargo@v1
        env:
          DEP_LV_CONFIG_PATH: /project/
        if: startsWith(github.ref, 'refs/tags/')
        with:
          use-cross: true
          command: build
          args: --target=thumbv7em-none-eabihf --all --locked --verbose --release

      - name: Build CoDiOS in debug mode
        uses: actions-rs/cargo@v1
        env:
          DEP_LV_CONFIG_PATH: /project/
        with:
          use-cross: true
          command: build
          args: --target=thumbv7em-none-eabihf --all --locked --verbose

      - name: If this build is a release, install cargo-binutils
        if: startsWith(github.ref, 'refs/tags/')
        run:
          cargo install cargo-binutils && rustup component add
          llvm-tools-preview

      - name: If this build is a release, strip the firmware image
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo strip --release -- --strip-all

      - name: Create release for CoDiOS
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/thumbv7em-none-eabihf/release/codios-firmware
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v2
        with:
          name: codios-firmware-debug
          path: ./target/thumbv7em-none-eabihf/debug/codios-firmware
